// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration options
class FirebaseOptions {
  final String apiKey;
  final String? appId;
  final String? messagingSenderId;
  final String? projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? iosBundleId;

  const FirebaseOptions({
    required this.apiKey,
    this.appId,
    this.messagingSenderId,
    this.projectId,
    this.authDomain,
    this.storageBucket,
    this.iosBundleId,
  });
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7sqjG68aoEDACCwe8gqHNgl-ZyV37MA',
    appId: '1:461801616252:web:1a0eef3d845094d71c6af9',
    messagingSenderId: '461801616252',
    projectId: 'al-mcq-quiz',
    authDomain: 'al-mcq-quiz.firebaseapp.com',
    storageBucket: 'al-mcq-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1r7lYYgt-2YhjaeIcqOlMZpWcEkDC9Us',
    appId: '1:461801616252:android:9705b0d67110da401c6af9',
    messagingSenderId: '461801616252',
    projectId: 'al-mcq-quiz',
    storageBucket: 'al-mcq-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbyOm2nEswv84wDu0cfj54JN8NSxnXIRA',
    appId: '1:461801616252:ios:e0c67057b020f43e1c6af9',
    messagingSenderId: '461801616252',
    projectId: 'al-mcq-quiz',
    storageBucket: 'al-mcq-quiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbyOm2nEswv84wDu0cfj54JN8NSxnXIRA',
    appId: '1:461801616252:ios:e0c67057b020f43e1c6af9',
    messagingSenderId: '461801616252',
    projectId: 'al-mcq-quiz',
    storageBucket: 'al-mcq-quiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7sqjG68aoEDACCwe8gqHNgl-ZyV37MA',
    appId: '1:461801616252:web:652aeb04d489b1c31c6af9',
    messagingSenderId: '461801616252',
    projectId: 'al-mcq-quiz',
    authDomain: 'al-mcq-quiz.firebaseapp.com',
    storageBucket: 'al-mcq-quiz.firebasestorage.app',
  );

}